# Generated by Django 2.2.3 on 2019-11-17 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_image', models.ImageField(upload_to='profile_pics')),
                ('race_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=200)),
                ('unit_image', models.ImageField(upload_to='profile_pics')),
                ('cost', models.IntegerField()),
                ('upkeep', models.IntegerField()),
                ('mp_cost', models.ImageField(upload_to='')),
                ('health', models.IntegerField()),
                ('health_per_entity', models.ImageField(upload_to='')),
                ('armour', models.IntegerField()),
                ('parry_chance', models.IntegerField()),
                ('ward_save', models.IntegerField()),
                ('physical_resistance', models.IntegerField()),
                ('missile_resistance', models.IntegerField()),
                ('magic_resistance', models.IntegerField()),
                ('fire_resistance', models.IntegerField()),
                ('leadership', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('melee_attack', models.IntegerField()),
                ('attack_interval', models.IntegerField()),
                ('melee_defence', models.IntegerField()),
                ('weapon_strenght', models.IntegerField()),
                ('base_damage', models.IntegerField()),
                ('ap_damage', models.IntegerField()),
                ('bonus_vs_large', models.IntegerField()),
                ('bonus_vs_infantry', models.IntegerField()),
                ('charge_bonus', models.IntegerField()),
                ('ammunition', models.IntegerField()),
                ('range', models.IntegerField()),
                ('missile_damage', models.IntegerField()),
                ('missile_base_damage', models.IntegerField()),
                ('missile_ap_damage', models.IntegerField()),
                ('missile_bonus_vs_infantry', models.IntegerField()),
                ('missile_bonus_vs_large', models.IntegerField()),
                ('explosion_base_damage', models.IntegerField()),
                ('explosion_ap_damage', models.IntegerField()),
                ('shot_per_volley', models.IntegerField()),
                ('projectile_number', models.IntegerField()),
                ('reload_time', models.IntegerField()),
                ('total_accuracy', models.IntegerField()),
                ('calibration_distance', models.IntegerField()),
                ('calibration_area', models.IntegerField()),
                ('fatigue_modifier', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhammerwiki.Race')),
            ],
        ),
    ]
