# Generated by Django 2.2.3 on 2019-11-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammerwiki', '0003_auto_20191117_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='melee_ap_yes_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='melee_bonus_inf_yes_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='melee_bonus_large_yes_no',
            field=models.BooleanField(default=False),
        ),
    ]
