# Generated by Django 2.2.3 on 2019-11-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammerwiki', '0004_auto_20191120_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='missile_ap_yes_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='missile_bonus_inf_yes_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='missile_bonus_large_yes_no',
            field=models.BooleanField(default=False),
        ),
    ]
