# Generated by Django 2.2.3 on 2019-11-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammerwiki', '0005_auto_20191120_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='contaminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='melee_fire_attack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='melee_magic_attack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='melee_poison_attack',
            field=models.BooleanField(default=False),
        ),
    ]
