# Generated by Django 2.2.3 on 2019-11-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammerwiki', '0006_auto_20191120_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='disturbed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='frostbite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='sundered_armour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='weeping_blade',
            field=models.BooleanField(default=False),
        ),
    ]
