# Generated by Django 2.2.3 on 2019-11-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammerwiki', '0007_auto_20191120_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='charmed',
            field=models.BooleanField(default=False),
        ),
    ]
