# Generated by Django 2.2.3 on 2019-11-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammerwiki', '0008_unit_charmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='blinded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='flammable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='missile_disturbed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='missile_fire_attack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='missile_magic_attack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='missile_poision_attack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='missile_sundered_armour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='monstrous_impact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='shieldbreaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='suppressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='zzzzap',
            field=models.BooleanField(default=False),
        ),
    ]
