# Generated by Django 2.2.3 on 2019-11-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammerwiki', '0009_auto_20191122_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='burnt',
            field=models.BooleanField(default=False),
        ),
    ]
