# Generated by Django 2.2.3 on 2019-11-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammerwiki', '0010_unit_burnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='bronze_shield',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='no_shield',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='silver_shield',
            field=models.BooleanField(default=False),
        ),
    ]
