# Generated by Django 2.2.3 on 2019-11-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhammerwiki', '0011_auto_20191122_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='no_shield',
        ),
    ]
